<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>pogolm_landmark_usage</name>
  <version>1.0.1</version>
  <description>This repository contains a small ROS 2 package that demonstrates landmark usage with the POGOLM API (`pgo_with_visual::pogolm_api`) by inserting landmarks from RViz “clicked point” inputs and using POGOLM’s neighbor query as a geometric heuristic for user-side data association.</description>
  <maintainer email="dsamuelyan@uos.de">Davit Samuelyan</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <depend>rclcpp</depend>
  <depend>nav_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>pgo_with_visual</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
